on: [push, pull_request, release, workflow_dispatch]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pluswerk/php-dev:nginx-${{ matrix.php }}
      options: -t
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
    name: 'PHP ${{ matrix.php }}'
    steps:
      - run: git config --global --add safe.directory /__w/ShellCommandBuilder/ShellCommandBuilder
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: vendor/bin/grumphp run
      - run: script -q -e -c "composer test"
      - run: script -q -e -c "composer infection"
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tests/test-results/coverage.xml
